from common import SignMode

DEFAULT_SIGN_MODE = SignMode.MTA
DEFAULT_MBTA_STATION = "place-harsq" # harvard square station
DEFAULT_MTA_STATION = "121" # 86 St 1,2,3 station
EMULATE_RGB_MATRIX = False
SPOTIFY_CLIENT_ID = ""
SPOTIFY_CLIENT_SECRET = ""
SPOTIFY_REFRESH_TOKEN = ""
MBTA_API_KEY = ""
IPDATA_API_KEY = ""
MTA_API_KEY = ""
MTA_FAKE_DATA = False