from common import SignMode

DEFAULT_SIGN_MODE = SignMode.MTA
EMULATE_RGB_MATRIX = False
SPOTIFY_CLIENT_ID = ""
SPOTIFY_CLIENT_SECRET = ""
SPOTIFY_REFRESH_TOKEN = ""
MBTA_API_KEY = ""
IPDATA_API_KEY = ""
MTA_API_KEY = ""
MTA_FAKE_DATA = False